# Memoracion, Jancen Johan
# 2ECEB

# Programming Assignment 2

Normalization Problem

In [1]:
#Syntax

In [2]:
import numpy as np

In [3]:
X = np.random.random((5,5))
X

array([[0.26931184, 0.98733178, 0.49044769, 0.99355321, 0.55554488],
       [0.34563286, 0.61711356, 0.36544708, 0.19020065, 0.51199233],
       [0.4239757 , 0.74387808, 0.13526557, 0.95684083, 0.23472773],
       [0.39615527, 0.39242564, 0.30277851, 0.17668034, 0.57982541],
       [0.36074766, 0.25625833, 0.96789324, 0.85645023, 0.40127063]])

In [16]:
Z = X.mean()/X.std()
Z

np.float64(1.8791337519904288)

In [14]:
np.save("X_normalized", Z)

Divisible by 3 Problem

In [6]:
#Syntax

In [7]:
import numpy as np

In [8]:
num = np.arange(1,101)
num

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
squared = num ** 2
squared

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

In [13]:
div_3 = squared[squared % 3 == 0]
div_3

In [ ]:
np.save("div_by_3", div_3)